package next.avinor.fmtpssm.domain;

public enum ConnectionEvent {
    INIT, LOCAL_SETUP, REMOTE_SETUP, REMOTE_ID_VALID, LOCAL_STARTUP, REMOTE_STARTUP, SHUTDOWN, DISCONNECT, TIMEOUT, HEARTBEAT, DATA, ID_INVALID, ACCEPT, REJECT, KILL, Unknown
}
